name: Continuous Integration

on: [ push ]

jobs:
  test:
    strategy:
      matrix:
        target:
          - os: 'windows-latest'
            goos: 'windows'
            goarch: 'amd64'
        go: [ '1.14' ]

    runs-on: ${{ matrix.target.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - run: go test -v
        env:
          GOOS: ${{ matrix.target.goos }}
          GOARCH: ${{ matrix.target.goarch }}

  build:
    strategy:
      matrix:
        target:
          - os: 'windows-latest'
            goos: 'windows'
            goarch: 'amd64'
        go: [ '1.14' ]

    runs-on: ${{ matrix.target.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - run: go build .\cmd\bat2exe.go
        env:
          GOOS: ${{ matrix.target.goos }}
          GOARCH: ${{ matrix.target.goarch }}